export * from "./About"
export * from "./BeforeAfter"
export * from "./Catalog"
export * from "./Faq"
export * from "./Footer"
export * from "./Header"
export * from "./Hero"
export * from "./Sertification"
export * from "./SertificationSlider"

export * from "./ServesStages"
export * from "./ServiseTable"
export * from "./Testimonials"
export * from "./TestimonialsSlider"

export * from "./ServesMain"
