export * from "./ArrowIcon"
export * from "./BurgerIcon"
export * from "./CatalogIcon"
export * from "./CertificateIcon"
export * from "./FlowerIcon"
export * from "./InfoIcon"
export * from "./InstagramIcon"
export * from "./LocationIcon"
export * from "./LogoIcon"
export * from "./PhoneIcon"
export * from "./StarIcon"
export * from "./StarReview"
export * from "./StarsIcon"

